language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
  
script: "pyb -X verify analyze"
after_success:
  - coveralls --verbose
